# Generated by Django 2.2.12 on 2020-05-28 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasonic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.IntegerField(verbose_name='distance')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='lat')),
                ('lng', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='lng')),
                ('area', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='area')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
